Adiciona a versão a partir da v0.58 ao tfsec
mentoriaiac/Makefiles pull request #24
Opened 2021-10-25 19:11 UTC by samyev

# Adiciona a versão a partir da v0.58 ao tfsec

- [x] Garanta que seu **topic/feature/bugfix branch** tenha uma branch nomeada e não a sua branch main esteja no PR
- [x] Dê um titulo que expresse o objetivo do PR
- [x] Associe seu PR a uma Issue criada no repositósito. Caso seja uma correção de linguagem ou pequenas correções, não é necessário
- [x] Descreva o objetivo do PR
- [ ] Inclua links relevantes para a sua modificação/sugestão/correção
- [x] Descreva um passo-a-passo para testar o seu PR

## Issue

close #23 

## Objetivo

O comando de execução do terraform-tfsec utiliza a imagem tfesc com a tag latest. Devemos especificar uma versão diferente da latest para este comando.

## Referências

N/A

## Como testar

Para testar, você deve ter o clone do projeto em sua máquina, depois siga a documentação para entender como utilizar o template. Em um terminal, ao entrar na pasta do projeto **Makefile**, execute o comando abaixo:

~~~shell
make terraform-tfsec
~~~

> Observação: Essa issue está dependente da issue #20, para o comando funcionar sem erros, deve ser removido o parâmetro **-u** da execução do comando **terraform-tfsec** no arquivo terraform.inc

Quando removido o parâmetro, o comando executa sem erros:

~~~shell
STEP: terraform-tfsec - Execute tfsec in terraform files

  times
  ------------------------------------------
  disk i/o             494.427µs
  parsing HCL          5.764µs
  evaluating values    50.402µs
  running checks       1.233327ms

  counts
  ------------------------------------------
  files loaded         2
  blocks               4
  modules              0

  results
  ------------------------------------------
  critical             0
  high                 0
  medium               0
  low                  0
  ignored              0

No problems detected!
~~~

2021-10-30 02:32 UTC, gomex approved these changes

2021-10-30 22:39 UTC, snifbr requested changes
Olá @samyev seu PR conflitou com as mudanças que estavam na fila para aprovação, é necessário que você aplique as atualizações mais recentes do repositório https://github.com/mentoriaiac/Makefiles na sua branch e atualize seu PR. Caso precise de ajuda com o processo no GIT, pode nos chamar no discord ou agendar algo que aparecemos para lhe ajudar.

Caso achar muito complicado fazer o processo todo na sua branch atual, pode fechar este PR e fazer um novo fork da branch main mais atual e abrir um novo PR já com a atualizações e sem conflitos.

2021-10-31 16:04 UTC, gomex submitted a review, later dismissed
Precisa resolver o conflito.

2021-11-01 15:33 UTC, samyev commented
Olá, apliquei as novas atualizações do repositório pra corrigir os conflitos e adicionei novamente a minha alteração, vocês podem me dizer se está tudo certinho? Qualquer coisa só dizer ^^

2021-11-02 02:51 UTC, snifbr approved these changes

2021-11-02 02:54 UTC, snifbr approved these changes
LGTM

2021-11-02 02:57 UTC, merged